name: Deploy Project
on: [push, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: yarn install
      - name: Run Lint
        run: yarn lint

  # test job
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: yarn install
      - name: Run Test
        run: yarn test

  # build job
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code
        uses: actions/checkout@3
      - name: Install Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: yarn install
      - name: Build Project
        run: yarn build
      - name: Deploy
        run: echo "Deployment..."
